version: "3.4"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      AWS_ACCESS_KEY_ID: ???
      AWS_SECRET_KEY: ???
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: kotlin_vertx
      MYSQL_ROOT_PASSWORD: password